language: go
sudo: required
go:
  - tip
  
services:
  - docker
  
script: 
  - go test .
  - export VERSION=`git describe --tag --long`
  - export GOVERSION=`go version`
  - echo VERSION is $VERSION
  - echo GOVERSION is $GOVERSION
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-X main.version=$VERSION -X main.goVersion="$GOVERSION"" -o gowebhello gowebhello.go
  - docker build -t wenism/gowebhello:$VERSION .
  - docker images
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wenism/gowebhello:$VERSION